# Generated by Django 4.1.2 on 2022-10-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_show_description_job_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='log_description',
            new_name='long_description',
        ),
    ]
