# Generated by Django 4.1.2 on 2022-10-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_company_address_job_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(choices=[('size-1_9', '1-9'), ('size-10_49', '10-49'), ('size-50_99', '50-99'), ('size-100', '100')], default='size-1_9', max_length=20),
        ),
    ]
