# Generated by Django 4.1.2 on 2022-10-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_conversationmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
